SERVER_IDLE_TIMEOUT: 5
SERVER_READ_TIMEOUT: 1
SERVER_WRITE_TIMEOUT: 1
SERVER_PORT: ":9003"
KAFKA_SERVER: "localhost:9092"
KAFKA_CONSUMER_GROUP: "transactionGroup"
HIGH_PRIORITY_PARTITION: 20
MEDIUM_PRIORITY_PARTITION: 10
LOW_PRIORITY_PARTITION: 5