SERVER_IDLE_TIMEOUT: 5
SERVER_READ_TIMEOUT: 1
SERVER_WRITE_TIMEOUT: 1
SERVER_PORT: ":9001"
KAFKA_SERVER: "localhost:9092"
KAFKA_CONSUMER_GROUP: "transactionGroup"
HIGH_PRIORITY_PARTITION: 10
MEDIUM_PRIORITY_PARTITION: 4
LOW_PRIORITY_PARTITION: 2